name: Run tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         python-version: [ 3.6, 3.7, 3.8, 3.9 ]

    steps:
          - name: Checkout repo
            uses: actions/checkout@v2
          - name: Set Up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install deps
            run: |
              sudo apt update
              sudo apt install acpica-tools
              python -m pip install --upgrade pip
              pip install ecdsa cached_property cstruct ctypeslib2 pyelftools pytest 

          - name: Run pytest
            run: |
              pip install ./
              pytest test
